---
apiVersion: zenith.stackhpc.com/v1alpha1
kind: Client
metadata:
  name: {{ include "ragflow-azimuth.fullname" . }}
  labels: {{ include "ragflow-azimuth.labels" . | nindent 4 }}
spec:
  reservationName: {{ include "ragflow-azimuth.fullname" . }}
  upstream:
    serviceName: {{ .Release.Name }}
  auth:
    skip: {{ .Values.zenithClient.skipAuth }}
---
apiVersion: zenith.stackhpc.com/v1alpha1
kind: Reservation
metadata:
  name: {{ include "ragflow-azimuth.fullname" . }}
  labels: {{ include "ragflow-azimuth.labels" . | nindent 4 }}
  annotations:
    azimuth.stackhpc.com/service-label: {{ quote .Values.zenithClient.label }}
    azimuth.stackhpc.com/service-icon-url: {{ .Values.zenithClient.iconUrl }}
    {{- with .Values.zenithClient.description }}
    azimuth.stackhpc.com/service-description: {{ quote . }}
    {{- end }}
spec:
  credentialSecretName: {{ include "ragflow-azimuth.fullname" . }}-credential
---
{{- if .Values.ragflow.apiProxy.enabled }}
apiVersion: zenith.stackhpc.com/v1alpha1
kind: Client
metadata:
  name: {{ include "ragflow-azimuth.fullname" . }}-api-proxy
  labels: {{ include "ragflow-azimuth.labels" . | nindent 4 }}
spec:
  reservationName: {{ include "ragflow-azimuth.fullname" . }}-api-proxy
  upstream:
    serviceName: {{ .Release.Name }}-api-proxy
  auth:
    {{/* NOTE(sd109): API is authenticated by RAGFlow API key */}}
    skip: true
---
apiVersion: zenith.stackhpc.com/v1alpha1
kind: Reservation
metadata:
  name: {{ include "ragflow-azimuth.fullname" . }}-api-proxy
  labels: {{ include "ragflow-azimuth.labels" . | nindent 4 }}
  annotations:
    azimuth.stackhpc.com/service-label: {{ printf "%s API" .Values.zenithClient.label }}
    azimuth.stackhpc.com/service-icon-url: {{ .Values.zenithClient.apiProxyIconUrl }}
    {{- with .Values.zenithClient.description }}
    azimuth.stackhpc.com/service-description: {{ quote . }}
    {{- end }}
spec:
  credentialSecretName: {{ include "ragflow-azimuth.fullname" . }}-api-proxy-credential
{{- end }}
